- name: Configuring prompt
  ansible.builtin.lineinfile: 
     path: ~/.bashrc
     line: export PS1="\[\e[1;31m\]\u\[\e[0m\]@\[\e[1;34m\]{{ role_name }}\[\e[0m\] \w \$"
     state: present
     create: true

- name:  Install chef work sttaion
  ansible.builtin.dnf: 
     name:  chef